name: NGS_master
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - abricate=0.7
  - alsa-lib=1.2.15.3
  - annotated-types=0.7.0
  - archspec=0.2.5
  - argcomplete=3.6.3
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - backports.zstd=1.3.0
  - bamtools=2.5.2
  - bcftools=1.21
  - beautifulsoup4=4.14.3
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.44
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocio=1.12.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-biostrings=2.70.1
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.28.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicalignments=1.38.0
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-noiseq=2.46.0
  - bioconductor-rhtslib=2.4.0
  - bioconductor-rsamtools=2.18.0
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - biopython=1.86
  - blast=2.16.0
  - bokeh=3.8.2
  - bowtie2=2.5.4
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bwa=0.7.19
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.0
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - contourpy=1.3.2
  - cpython=3.10.19
  - curl=8.18.0
  - cutadapt=5.2
  - cycler=0.12.1
  - cytoolz=1.1.0
  - dask=2026.1.2
  - dask-core=2026.1.2
  - diamond=0.8.36
  - distributed=2026.1.2
  - dnaio=1.2.2
  - emboss=6.6.0
  - entrez-direct=22.4
  - exceptiongroup=1.3.1
  - expat=2.7.4
  - fastqc=0.12.1
  - filetype=1.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2026.1.0
  - gatk4=4.6.2.0
  - gcc_impl_linux-64=15.2.0
  - gflags=2.2.2
  - gfortran_impl_linux-64=15.2.0
  - giflib=5.2.2
  - glog=0.7.1
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.2.0
  - h2=4.3.0
  - harfbuzz=12.3.0
  - hmmer=3.4
  - hpack=4.1.0
  - htslib=1.21
  - humanfriendly=10.0
  - humanize=4.15.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - isa-l=2.31.1
  - jinja2=3.1.6
  - jq=1.5
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - kaleido-core=0.2.1
  - kernel-headers_linux-64=6.12.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - kma=1.6.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.18.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.4
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libharu=2.4.5
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsanitizer=15.2.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.11.3
  - libuuid=1.41.5
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - locket=1.0.0
  - lxml=6.0.2
  - lz4=4.4.5
  - lz4-c=1.10.0
  - make=4.4.1
  - markdown=3.10.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mathjax=2.7.7
  - matplotlib-base=3.10.8
  - mdurl=0.1.2
  - mlst=2.11
  - mpi=1.0
  - msgpack-python=1.1.2
  - multiqc=1.33
  - munkres=1.0.7
  - narwhals=2.16.0
  - natsort=8.4.0
  - ncbi-amrfinderplus=4.2.7
  - ncbi-vdb=3.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nspr=4.38
  - nss=3.118
  - numpy=2.2.6
  - oligoarrayaux=3.8
  - openjdk=25.0.1
  - openjpeg=2.5.3
  - openmpi=4.1.6
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.54.0
  - partd=1.4.2
  - pbzip2=1.1.13
  - pcre2=10.44
  - perl=5.22.0.1
  - perl-app-cpanminus=1.7043
  - perl-archive-tar=2.18
  - perl-bioperl=1.6.924
  - perl-carp=1.38
  - perl-class-method-modifiers=2.11
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.069
  - perl-compress-raw-zlib=2.069
  - perl-data-dumper=2.161
  - perl-devel-globaldestruction=0.13
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-exporter-tiny=0.042
  - perl-extutils-makemaker=7.24
  - perl-file-slurp=9999.19
  - perl-file-spec=3.48_01
  - perl-findbin=1.51
  - perl-io-compress=2.069
  - perl-io-zlib=1.10
  - perl-json=2.90
  - perl-json-xs=2.34
  - perl-list-moreutils=0.428
  - perl-lwp-simple=6.15
  - perl-module-runtime=0.014
  - perl-moo=2.001000
  - perl-pathtools=3.73
  - perl-role-tiny=2.000001
  - perl-scalar-list-utils=1.45
  - perl-sub-exporter-progressive=0.001011
  - perl-test-more=1.001002
  - perl-text-csv=1.33
  - perl-threaded=5.32.1
  - perl-yaml=1.24
  - picard=3.4.0
  - pigz=2.8
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - plotly=6.5.2
  - pluggy=1.6.0
  - polars=1.38.0
  - polars-lts-cpu=1.34.0.deprecated
  - polars-runtime-32=1.38.0
  - polars-runtime-compat=1.38.0
  - prodigal=2.6.3
  - prometheus-cpp=1.3.0
  - psutil=7.2.2
  - pthread-stubs=0.3
  - pyahocorasick=2.1.0
  - pyaml-env=1.2.2
  - pyarrow=22.0.0
  - pyarrow-core=22.0.0
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pyfaidx=0.9.0.3
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pyrodigal=3.7.0
  - pysam=0.22.1
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-gil=3.10.19
  - python-isal=1.8.0
  - python-kaleido=0.2.1
  - python-tzdata=2025.3
  - python-zlib-ng=1.0.0
  - python_abi=3.10
  - pytz=2025.2
  - pyvcf3=1.0.4
  - pyyaml=6.0.3
  - qhull=2020.2
  - qualimap=2.3
  - r-abind=1.4_5
  - r-base=4.3.3
  - r-bh=1.87.0_1
  - r-bitops=1.0_9
  - r-codetools=0.2_20
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-formatr=1.14
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.4
  - r-lambda.r=1.2.4
  - r-lattice=0.22_7
  - r-matrix=1.6_5
  - r-matrixstats=1.5.0
  - r-optparse=1.7.5
  - r-rcurl=1.98_1.16
  - r-restfulr=0.0.15
  - r-rjson=0.2.23
  - r-snow=0.4_4
  - r-xml=3.99_0.17
  - r-yaml=2.3.10
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - regex=2026.1.15
  - requests=2.32.4
  - rgi=6.0.5
  - rich=14.3.2
  - rich-click=1.9.7
  - rpds-py=0.30.0
  - rpsbproc=0.5.1
  - s2n=1.6.2
  - samtools=1.21
  - scipy=1.15.2
  - seaborn-base=0.13.2
  - sed=4.9
  - setuptools=80.10.2
  - six=1.17.0
  - snappy=1.2.2
  - snpeff=5.4.0a
  - snpsift=5.4.0a
  - sortedcontainers=2.4.0
  - soupsieve=2.8.3
  - spectra=0.0.11
  - sqlite=3.51.1
  - sysroot_linux-64=2.39
  - tabix=1.11
  - tblib=3.2.2
  - tiktoken=0.12.0
  - tk=8.6.15
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.4.0
  - tomlkit=0.14.0
  - toolz=1.1.0
  - tornado=6.5.4
  - tqdm=4.67.3
  - trim-galore=0.6.10
  - trimmomatic=0.40
  - typeguard=4.4.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - unzip=6.0
  - urllib3=2.6.3
  - vcftools=0.1.14
  - wget=1.21.4
  - wheel=0.46.3
  - xmltodict=1.0.2
  - xopen=2.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - yq=3.4.3
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/manojdevadiga286/miniconda3/envs/NGS_master
